name: 🚀 Deploy website on push

on:
  push:
    branches:
      - "main"

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp-sktusher.alwaysdata.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          security: strict
          passive: true  # ✅ Passive mode for better connectivity
          concurrency: 1  # ✅ Upload files one by one
          retries: 5  # ✅ Retry failed uploads
