name: 🚀 Deploy website on push

on:
  push:
    branches:
      - "main"

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.yourdomain.alwaysdata.net # Change this to your Alwaysdata FTP host
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps # ✅ Use FTPS for secure connection
          security: strict # ✅ Enforce secure TLS connection
          passive: true # ✅ Alwaysdata requires passive mode
          concurrency: 1 # ✅ Upload files one by one to prevent connection issues
          retries: 5 # ✅ Retry failed uploads up to 5 times
          delayBetweenUpdates: 500 # ✅ Add 500ms delay between uploads to avoid disconnections
