name: 🚀 Deploy website on push

on:
  push:
    branches:
      - "main"

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp-sktusher.alwaysdata.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps # Use `ftp` if FTPS is not supported
    security: loose # Try `loose` if `strict` fails
    timeout: 300 # Increase timeout to 300 seconds (5 mins)
    log-level: verbose # Enable detailed logs for debugging
